.TH "ContextFreeGrammars.Infrastructure/bitmaskutil.cpp" 3 "Tue Jun 4 2019" "Context-Free Grammars" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ContextFreeGrammars.Infrastructure/bitmaskutil.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'stdafx\&.h'\fP
.br
\fC#include 'bitmaskutil\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBtry_advance_bitmask\fP (vector< bool > &bitset)"
.br
.ti -1c
.RI "bool \fBis_all_false\fP (const std::vector< bool > &bitmask)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "bool is_all_false (const std::vector< bool > & bitmask)"

.SS "bool try_advance_bitmask (vector< bool > & bitset)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Context-Free Grammars from the source code\&.
