.TH "ContextFreeGrammars.CLI/cfg_cli.cpp" 3 "Tue Jun 4 2019" "Context-Free Grammars" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ContextFreeGrammars.CLI/cfg_cli.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'pch\&.h'\fP
.br
\fC#include 'cfg_cli\&.h'\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <filesystem>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include '\&.\&./ContextFreeGrammars\&.Grammars/grammar\&.h'\fP
.br
\fC#include '\&.\&./ContextFreeGrammars\&.Infrastructure/stringutil\&.h'\fP
.br
\fC#include '\&.\&./ContextFreeGrammars\&.Serialization/informal_grammar_serialization\&.h'\fP
.br
\fC#include '\&.\&./ContextFreeGrammars\&.Deserialization/grammar_deserialization\&.h'\fP
.br
\fC#include '\&.\&./ContextFreeGrammars\&.Serialization/grammar_serialization\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Context-Free Grammars from the source code\&.
