.TH "command" 3 "Tue Jun 4 2019" "Context-Free Grammars" \" -*- nroff -*-
.ad l
.nh
.SH NAME
command
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cfg_cli\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBcommand\fP ()"
.br
.ti -1c
.RI "\fBcommand\fP (const std::string &\fBname\fP, const std::vector< std::string > &\fBarguments\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBname\fP"
.br
.ti -1c
.RI "std::vector< std::string > \fBarguments\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "command::command ()\fC [inline]\fP"

.SS "command::command (const std::string & name, const std::vector< std::string > & arguments)\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "std::vector<std::string> command::arguments"

.SS "std::string command::name"


.SH "Author"
.PP 
Generated automatically by Doxygen for Context-Free Grammars from the source code\&.
