.TH "concatenation" 3 "Tue Jun 4 2019" "Context-Free Grammars" \" -*- nroff -*-
.ad l
.nh
.SH NAME
concatenation
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <concatenation\&.h>\fP
.PP
Inherits \fBvariable_arity_operator< term >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBconcatenation\fP ()"
.br
.ti -1c
.RI "\fBconcatenation\fP (const char *toWrap)"
.br
.ti -1c
.RI "\fBconcatenation\fP (const std::string &toWrap)"
.br
.ti -1c
.RI "\fBconcatenation\fP (const \fBterm\fP &toWrap)"
.br
.ti -1c
.RI "\fBconcatenation\fP (const \fBconcatenation\fP &toCopy)"
.br
.ti -1c
.RI "\fBconcatenation\fP & \fBoperator=\fP (const \fBconcatenation\fP &toAssign)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "concatenation::concatenation ()\fC [inline]\fP"

.SS "concatenation::concatenation (const char * toWrap)\fC [inline]\fP"

.SS "concatenation::concatenation (const std::string & toWrap)\fC [inline]\fP"

.SS "concatenation::concatenation (const \fBterm\fP & toWrap)"

.SS "concatenation::concatenation (const \fBconcatenation\fP & toCopy)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBconcatenation\fP & concatenation::operator= (const \fBconcatenation\fP & toAssign)"


.SH "Author"
.PP 
Generated automatically by Doxygen for Context-Free Grammars from the source code\&.
