.TH "document_position" 3 "Tue Jun 4 2019" "Context-Free Grammars" \" -*- nroff -*-
.ad l
.nh
.SH NAME
document_position
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <document_position\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBdocument_position\fP ()"
.br
.ti -1c
.RI "\fBdocument_position\fP (int \fBrow\fP, int \fBcolumn\fP, int \fBcharacterSpan\fP)"
.br
.ti -1c
.RI "\fBdocument_position\fP (int \fBrow\fP, int \fBcolumn\fP, int \fBcharacterSpan\fP, int \fBrowsAdded\fP)"
.br
.ti -1c
.RI "int \fBrow\fP () const"
.br
.ti -1c
.RI "void \fBset_row\fP (int \fBrow\fP)"
.br
.ti -1c
.RI "int \fBcolumn\fP () const"
.br
.ti -1c
.RI "void \fBset_column\fP (int \fBcolumn\fP)"
.br
.ti -1c
.RI "int \fBcharacter_span\fP () const"
.br
.ti -1c
.RI "void \fBset_character_span\fP (int \fBcharacterSpan\fP)"
.br
.ti -1c
.RI "int \fBrows_added\fP () const"
.br
.ti -1c
.RI "void \fBset_rows_added\fP (int \fBrowsAdded\fP)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "document_position::document_position ()\fC [inline]\fP"

.SS "document_position::document_position (int row, int column, int characterSpan)\fC [inline]\fP"

.SS "document_position::document_position (int row, int column, int characterSpan, int rowsAdded)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "int document_position::character_span () const\fC [inline]\fP"

.SS "int document_position::column () const\fC [inline]\fP"

.SS "int document_position::row () const\fC [inline]\fP"

.SS "int document_position::rows_added () const\fC [inline]\fP"

.SS "void document_position::set_character_span (int characterSpan)\fC [inline]\fP"

.SS "void document_position::set_column (int column)\fC [inline]\fP"

.SS "void document_position::set_row (int row)\fC [inline]\fP"

.SS "void document_position::set_rows_added (int rowsAdded)\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "int document_position::characterSpan"

.SS "int document_position::column"

.SS "int document_position::row"

.SS "int document_position::rowsAdded"


.SH "Author"
.PP 
Generated automatically by Doxygen for Context-Free Grammars from the source code\&.
