.TH "ContextFreeGrammars.Serialization/grammar_serialization.cpp" 3 "Tue Jun 4 2019" "Context-Free Grammars" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ContextFreeGrammars.Serialization/grammar_serialization.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'stdafx\&.h'\fP
.br
\fC#include 'grammar_serialization\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "std::ostream & \fBserialize_grammar\fP (std::ostream &stream, const \fBgrammar\fP &\fBgrammar\fP)"
.br
.ti -1c
.RI "std::ostream & \fBserialize_named_rule\fP (std::ostream &stream, const std::string &name, const \fBproduction\fP &rule)"
.br
.ti -1c
.RI "std::ostream & \fBserialize_rule\fP (std::ostream &stream, const \fBproduction\fP &rule)"
.br
.ti -1c
.RI "std::ostream & \fBserialize_concatenation\fP (std::ostream &stream, const \fBconcatenation\fP &\fBconcatenation\fP)"
.br
.ti -1c
.RI "std::ostream & \fBserialize_production_term\fP (std::ostream &stream, const \fBterm\fP &\fBterm\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "std::ostream& serialize_concatenation (std::ostream & stream, const \fBconcatenation\fP & concatenation)"

.SS "std::ostream& serialize_grammar (std::ostream & stream, const \fBgrammar\fP & grammar)"

.SS "std::ostream& serialize_named_rule (std::ostream & stream, const std::string & name, const \fBproduction\fP & rule)"

.SS "std::ostream& serialize_production_term (std::ostream & stream, const \fBterm\fP & term)"

.SS "std::ostream& serialize_rule (std::ostream & stream, const \fBproduction\fP & rule)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Context-Free Grammars from the source code\&.
