.TH "packages/Microsoft.googletest.v140.windesktop.msvcstl.static.rt-dyn.1.8.0/build/native/include/gtest/gtest-typed-test.h" 3 "Tue Jun 4 2019" "Context-Free Grammars" \" -*- nroff -*-
.ad l
.nh
.SH NAME
packages/Microsoft.googletest.v140.windesktop.msvcstl.static.rt-dyn.1.8.0/build/native/include/gtest/gtest-typed-test.h
.SH SYNOPSIS
.br
.PP
\fC#include 'gtest/internal/gtest\-port\&.h'\fP
.br
\fC#include 'gtest/internal/gtest\-type\-util\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Context-Free Grammars from the source code\&.
