.TH "packages/Microsoft.googletest.v140.windesktop.msvcstl.static.rt-dyn.1.8.0/build/native/include/gtest/gtest-death-test.h" 3 "Tue Jun 4 2019" "Context-Free Grammars" \" -*- nroff -*-
.ad l
.nh
.SH NAME
packages/Microsoft.googletest.v140.windesktop.msvcstl.static.rt-dyn.1.8.0/build/native/include/gtest/gtest-death-test.h
.SH SYNOPSIS
.br
.PP
\fC#include 'gtest/internal/gtest\-death\-test\-internal\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBtesting\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBEXPECT_DEATH_IF_SUPPORTED\fP(statement,  regex)   \fBGTEST_UNSUPPORTED_DEATH_TEST_\fP(statement, regex, )"
.br
.ti -1c
.RI "#define \fBASSERT_DEATH_IF_SUPPORTED\fP(statement,  regex)   \fBGTEST_UNSUPPORTED_DEATH_TEST_\fP(statement, regex, return)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBtesting::GTEST_DECLARE_string_\fP (death_test_style)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define ASSERT_DEATH_IF_SUPPORTED(statement, regex)   \fBGTEST_UNSUPPORTED_DEATH_TEST_\fP(statement, regex, return)"

.SS "#define EXPECT_DEATH_IF_SUPPORTED(statement, regex)   \fBGTEST_UNSUPPORTED_DEATH_TEST_\fP(statement, regex, )"

.SH "Author"
.PP 
Generated automatically by Doxygen for Context-Free Grammars from the source code\&.
