.TH "packages/Microsoft.googletest.v140.windesktop.msvcstl.static.rt-dyn.1.8.0/build/native/include/gtest/gtest-message.h" 3 "Tue Jun 4 2019" "Context-Free Grammars" \" -*- nroff -*-
.ad l
.nh
.SH NAME
packages/Microsoft.googletest.v140.windesktop.msvcstl.static.rt-dyn.1.8.0/build/native/include/gtest/gtest-message.h
.SH SYNOPSIS
.br
.PP
\fC#include <limits>\fP
.br
\fC#include 'gtest/internal/gtest\-port\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBtesting::Message\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBtesting\fP"
.br
.ti -1c
.RI " \fBtesting::internal\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBoperator<<\fP (const testing::internal::Secret &, int)"
.br
.ti -1c
.RI "std::ostream & \fBtesting::operator<<\fP (std::ostream &os, const Message &sb)"
.br
.ti -1c
.RI "template<typename T > std::string \fBtesting::internal::StreamableToString\fP (const T &streamable)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void operator<< (const testing::internal::Secret &, int)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Context-Free Grammars from the source code\&.
