.TH "ContextFreeGrammars.Serialization/informal_grammar_serialization.cpp" 3 "Tue Jun 4 2019" "Context-Free Grammars" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ContextFreeGrammars.Serialization/informal_grammar_serialization.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'stdafx\&.h'\fP
.br
\fC#include 'informal_grammar_serialization\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &stream, const \fBgrammar\fP &\fBgrammar\fP)"
.br
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &stream, const \fBproduction\fP &\fBproduction\fP)"
.br
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &stream, const \fBconcatenation\fP &\fBconcatenation\fP)"
.br
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &stream, const \fBterm\fP &\fBterm\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "std::ostream& operator<< (std::ostream & stream, const \fBgrammar\fP & grammar)"

.SS "std::ostream& operator<< (std::ostream & stream, const \fBproduction\fP & production)"

.SS "std::ostream& operator<< (std::ostream & stream, const \fBconcatenation\fP & concatenation)"

.SS "std::ostream& operator<< (std::ostream & stream, const \fBterm\fP & term)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Context-Free Grammars from the source code\&.
