.TH "ContextFreeGrammars.Deserialization/lookahead_tokenizer.h" 3 "Tue Jun 4 2019" "Context-Free Grammars" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ContextFreeGrammars.Deserialization/lookahead_tokenizer.h
.SH SYNOPSIS
.br
.PP
\fC#include 'stdafx\&.h'\fP
.br
\fC#include 'tokenizer\&.h'\fP
.br
\fC#include <iosfwd>\fP
.br
\fC#include <functional>\fP
.br
\fC#include <climits>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBlookahead_tokenizer\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Context-Free Grammars from the source code\&.
