.TH "ContextFreeGrammars.Grammars/production.h" 3 "Tue Jun 4 2019" "Context-Free Grammars" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ContextFreeGrammars.Grammars/production.h
.SH SYNOPSIS
.br
.PP
\fC#include 'concatenation\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBproduction\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Context-Free Grammars from the source code\&.
