.TH "std::tr1::tuple<>" 3 "Tue Jun 4 2019" "Context-Free Grammars" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::tr1::tuple<>
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gtest\-tuple\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtuple\fP ()"
.br
.ti -1c
.RI "\fBtuple\fP (const \fBtuple\fP &)"
.br
.ti -1c
.RI "\fBtuple\fP & \fBoperator=\fP (const \fBtuple\fP &)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBstd::tr1::tuple\fP<>::\fBtuple\fP ()\fC [inline]\fP"

.SS "\fBstd::tr1::tuple\fP<>::\fBtuple\fP (const \fBtuple\fP<> &)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBtuple\fP& \fBstd::tr1::tuple\fP<>::operator= (const \fBtuple\fP<> &)\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Context-Free Grammars from the source code\&.
