.TH "std::tr1::tuple_size< GTEST_4_TUPLE_(T) >" 3 "Tue Jun 4 2019" "Context-Free Grammars" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::tr1::tuple_size< GTEST_4_TUPLE_(T) >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gtest\-tuple\&.h>\fP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const int \fBvalue\fP = 4"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "template<GTEST_4_TYPENAMES_(T) > const int \fBstd::tr1::tuple_size\fP< \fBGTEST_4_TUPLE_\fP(T) >::value = 4\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Context-Free Grammars from the source code\&.
