.TH "std::tr1::gtest_internal::SameSizeTuplePrefixComparator< 0, 0 >" 3 "Tue Jun 4 2019" "Context-Free Grammars" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::tr1::gtest_internal::SameSizeTuplePrefixComparator< 0, 0 >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gtest\-tuple\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "template<class Tuple1 , class Tuple2 > static bool \fBEq\fP (const Tuple1 &, const Tuple2 &)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "template<class Tuple1 , class Tuple2 > static bool \fBstd::tr1::gtest_internal::SameSizeTuplePrefixComparator\fP< 0, 0 >::Eq (const Tuple1 &, const Tuple2 &)\fC [inline]\fP, \fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Context-Free Grammars from the source code\&.
