.TH "std::tr1::gtest_internal::Get< 1 >" 3 "Tue Jun 4 2019" "Context-Free Grammars" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::tr1::gtest_internal::Get< 1 >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gtest\-tuple\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "template<class Tuple > static \fBGTEST_ADD_REF_\fP (\fBGTEST_TUPLE_ELEMENT_\fP(1, Tuple)) Field(Tuple &t)"
.br
.ti -1c
.RI "template<class Tuple > static \fBGTEST_BY_REF_\fP (\fBGTEST_TUPLE_ELEMENT_\fP(1, Tuple)) ConstField(const Tuple &t)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "template<class Tuple > static \fBstd::tr1::gtest_internal::Get\fP< 1 >::GTEST_ADD_REF_ (\fBGTEST_TUPLE_ELEMENT_\fP(1, Tuple)) &\fC [inline]\fP, \fC [static]\fP"

.SS "template<class Tuple > static \fBstd::tr1::gtest_internal::Get\fP< 1 >::GTEST_BY_REF_ (\fBGTEST_TUPLE_ELEMENT_\fP(1, Tuple)) const &\fC [inline]\fP, \fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Context-Free Grammars from the source code\&.
