.TH "std::tr1::gtest_internal::AddRef< T & >" 3 "Tue Jun 4 2019" "Context-Free Grammars" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::tr1::gtest_internal::AddRef< T & >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gtest\-tuple\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef T & \fBtype\fP"
.br
.in -1c
.SH "Member Typedef Documentation"
.PP 
.SS "template<typename T > typedef T& \fBstd::tr1::gtest_internal::AddRef\fP< T & >::\fBtype\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Context-Free Grammars from the source code\&.
