.TH "ContextFreeGrammars.Grammars/term.h" 3 "Tue Jun 4 2019" "Context-Free Grammars" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ContextFreeGrammars.Grammars/term.h
.SH SYNOPSIS
.br
.PP
\fC#include 'stdafx\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBterm\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBterm_type\fP : char { \fBterm_type::terminal\fP = 't', \fBterm_type::rule_reference\fP = 'r' }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBterm_type\fP : char\fC [strong]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIterminal \fP\fP
.TP
\fB\fIrule_reference \fP\fP
.SH "Author"
.PP 
Generated automatically by Doxygen for Context-Free Grammars from the source code\&.
