.TH "testing::EmptyTestEventListener" 3 "Tue Jun 4 2019" "Context-Free Grammars" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::EmptyTestEventListener
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gtest\&.h>\fP
.PP
Inherits \fBtesting::TestEventListener\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBOnTestProgramStart\fP (const \fBUnitTest\fP &)"
.br
.ti -1c
.RI "virtual void \fBOnTestIterationStart\fP (const \fBUnitTest\fP &, int)"
.br
.ti -1c
.RI "virtual void \fBOnEnvironmentsSetUpStart\fP (const \fBUnitTest\fP &)"
.br
.ti -1c
.RI "virtual void \fBOnEnvironmentsSetUpEnd\fP (const \fBUnitTest\fP &)"
.br
.ti -1c
.RI "virtual void \fBOnTestCaseStart\fP (const \fBTestCase\fP &)"
.br
.ti -1c
.RI "virtual void \fBOnTestStart\fP (const \fBTestInfo\fP &)"
.br
.ti -1c
.RI "virtual void \fBOnTestPartResult\fP (const \fBTestPartResult\fP &)"
.br
.ti -1c
.RI "virtual void \fBOnTestEnd\fP (const \fBTestInfo\fP &)"
.br
.ti -1c
.RI "virtual void \fBOnTestCaseEnd\fP (const \fBTestCase\fP &)"
.br
.ti -1c
.RI "virtual void \fBOnEnvironmentsTearDownStart\fP (const \fBUnitTest\fP &)"
.br
.ti -1c
.RI "virtual void \fBOnEnvironmentsTearDownEnd\fP (const \fBUnitTest\fP &)"
.br
.ti -1c
.RI "virtual void \fBOnTestIterationEnd\fP (const \fBUnitTest\fP &, int)"
.br
.ti -1c
.RI "virtual void \fBOnTestProgramEnd\fP (const \fBUnitTest\fP &)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "virtual void testing::EmptyTestEventListener::OnEnvironmentsSetUpEnd (const \fBUnitTest\fP &)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBtesting::TestEventListener\fP\&.
.SS "virtual void testing::EmptyTestEventListener::OnEnvironmentsSetUpStart (const \fBUnitTest\fP &)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBtesting::TestEventListener\fP\&.
.SS "virtual void testing::EmptyTestEventListener::OnEnvironmentsTearDownEnd (const \fBUnitTest\fP &)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBtesting::TestEventListener\fP\&.
.SS "virtual void testing::EmptyTestEventListener::OnEnvironmentsTearDownStart (const \fBUnitTest\fP &)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBtesting::TestEventListener\fP\&.
.SS "virtual void testing::EmptyTestEventListener::OnTestCaseEnd (const \fBTestCase\fP &)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBtesting::TestEventListener\fP\&.
.SS "virtual void testing::EmptyTestEventListener::OnTestCaseStart (const \fBTestCase\fP &)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBtesting::TestEventListener\fP\&.
.SS "virtual void testing::EmptyTestEventListener::OnTestEnd (const \fBTestInfo\fP &)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBtesting::TestEventListener\fP\&.
.SS "virtual void testing::EmptyTestEventListener::OnTestIterationEnd (const \fBUnitTest\fP &, int)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBtesting::TestEventListener\fP\&.
.SS "virtual void testing::EmptyTestEventListener::OnTestIterationStart (const \fBUnitTest\fP &, int)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBtesting::TestEventListener\fP\&.
.SS "virtual void testing::EmptyTestEventListener::OnTestPartResult (const \fBTestPartResult\fP &)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBtesting::TestEventListener\fP\&.
.SS "virtual void testing::EmptyTestEventListener::OnTestProgramEnd (const \fBUnitTest\fP &)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBtesting::TestEventListener\fP\&.
.SS "virtual void testing::EmptyTestEventListener::OnTestProgramStart (const \fBUnitTest\fP &)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBtesting::TestEventListener\fP\&.
.SS "virtual void testing::EmptyTestEventListener::OnTestStart (const \fBTestInfo\fP &)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBtesting::TestEventListener\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Context-Free Grammars from the source code\&.
