.TH "testing_internal" 3 "Tue Jun 4 2019" "Context-Free Grammars" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing_internal
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename T > void \fBDefaultPrintNonContainerTo\fP (const T &value, ::std::ostream *os)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "template<typename T > void testing_internal::DefaultPrintNonContainerTo (const T & value, ::std::ostream * os)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Context-Free Grammars from the source code\&.
