.TH "testing::internal::ScopedTrace" 3 "Tue Jun 4 2019" "Context-Free Grammars" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::ScopedTrace
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gtest\-internal\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBScopedTrace\fP (const char *file, int line, const \fBMessage\fP &message)"
.br
.ti -1c
.RI "\fB~ScopedTrace\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "testing::internal::ScopedTrace::ScopedTrace (const char * file, int line, const \fBMessage\fP & message)"

.SS "testing::internal::ScopedTrace::~ScopedTrace ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for Context-Free Grammars from the source code\&.
