.TH "testing::internal::RemoveConst< const T[N]>" 3 "Tue Jun 4 2019" "Context-Free Grammars" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::RemoveConst< const T[N]>
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gtest\-internal\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBRemoveConst\fP< T >::type \fBtype\fP[N]"
.br
.in -1c
.SH "Member Typedef Documentation"
.PP 
.SS "template<typename T , size_t N> typedef \fBRemoveConst\fP<T>::type \fBtesting::internal::RemoveConst\fP< const T[N]>::type[N]"


.SH "Author"
.PP 
Generated automatically by Doxygen for Context-Free Grammars from the source code\&.
