.TH "testing::internal::FormatForComparison< ToPrint, OtherOperand >" 3 "Tue Jun 4 2019" "Context-Free Grammars" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::FormatForComparison< ToPrint, OtherOperand >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gtest\-printers\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "::std::string \fBFormat\fP (const ToPrint &value)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "template<typename ToPrint , typename OtherOperand > ::std::string \fBtesting::internal::FormatForComparison\fP< ToPrint, OtherOperand >::Format (const ToPrint & value)\fC [inline]\fP, \fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Context-Free Grammars from the source code\&.
