.TH "testing::internal::scoped_ptr< T >" 3 "Tue Jun 4 2019" "Context-Free Grammars" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::scoped_ptr< T >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gtest\-port\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef T \fBelement_type\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBscoped_ptr\fP (T *p=NULL)"
.br
.ti -1c
.RI "\fB~scoped_ptr\fP ()"
.br
.ti -1c
.RI "T & \fBoperator *\fP () const"
.br
.ti -1c
.RI "T * \fBoperator\->\fP () const"
.br
.ti -1c
.RI "T * \fBget\fP () const"
.br
.ti -1c
.RI "T * \fBrelease\fP ()"
.br
.ti -1c
.RI "void \fBreset\fP (T *p=NULL)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "void \fBswap\fP (\fBscoped_ptr\fP &a, \fBscoped_ptr\fP &b)"
.br
.in -1c
.SH "Member Typedef Documentation"
.PP 
.SS "template<typename T> typedef T \fBtesting::internal::scoped_ptr\fP< T >::\fBelement_type\fP"

.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename T> \fBtesting::internal::scoped_ptr\fP< T >::\fBscoped_ptr\fP (T * p = \fCNULL\fP)\fC [inline]\fP, \fC [explicit]\fP"

.SS "template<typename T> \fBtesting::internal::scoped_ptr\fP< T >::~\fBscoped_ptr\fP ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<typename T> T* \fBtesting::internal::scoped_ptr\fP< T >::get () const\fC [inline]\fP"

.SS "template<typename T> T& \fBtesting::internal::scoped_ptr\fP< T >::operator * () const\fC [inline]\fP"

.SS "template<typename T> T* \fBtesting::internal::scoped_ptr\fP< T >::operator\-> () const\fC [inline]\fP"

.SS "template<typename T> T* \fBtesting::internal::scoped_ptr\fP< T >::release ()\fC [inline]\fP"

.SS "template<typename T> void \fBtesting::internal::scoped_ptr\fP< T >::reset (T * p = \fCNULL\fP)\fC [inline]\fP"

.SH "Friends And Related Function Documentation"
.PP 
.SS "template<typename T> void swap (\fBscoped_ptr\fP< T > & a, \fBscoped_ptr\fP< T > & b)\fC [friend]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Context-Free Grammars from the source code\&.
