.TH "testing::internal::SingleFailureChecker" 3 "Tue Jun 4 2019" "Context-Free Grammars" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::SingleFailureChecker
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gtest\-spi\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSingleFailureChecker\fP (const \fBTestPartResultArray\fP *results, \fBTestPartResult::Type\fP type, const \fBstring\fP &substr)"
.br
.ti -1c
.RI "\fB~SingleFailureChecker\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "testing::internal::SingleFailureChecker::SingleFailureChecker (const \fBTestPartResultArray\fP * results, \fBTestPartResult::Type\fP type, const \fBstring\fP & substr)"

.SS "testing::internal::SingleFailureChecker::~SingleFailureChecker ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for Context-Free Grammars from the source code\&.
