.TH "testing::internal::Random" 3 "Tue Jun 4 2019" "Context-Free Grammars" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::Random
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gtest\-internal\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRandom\fP (\fBUInt32\fP seed)"
.br
.ti -1c
.RI "void \fBReseed\fP (\fBUInt32\fP seed)"
.br
.ti -1c
.RI "\fBUInt32\fP \fBGenerate\fP (\fBUInt32\fP range)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const \fBUInt32\fP \fBkMaxRange\fP = 1u << 31"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "testing::internal::Random::Random (\fBUInt32\fP seed)\fC [inline]\fP, \fC [explicit]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBUInt32\fP testing::internal::Random::Generate (\fBUInt32\fP range)"

.SS "void testing::internal::Random::Reseed (\fBUInt32\fP seed)\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "const \fBUInt32\fP testing::internal::Random::kMaxRange = 1u << 31\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Context-Free Grammars from the source code\&.
