.TH "testing::internal::StaticAssertTypeEqHelper< T, T >" 3 "Tue Jun 4 2019" "Context-Free Grammars" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::StaticAssertTypeEqHelper< T, T >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gtest\-port\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum { \fBvalue\fP = true }"
.br
.in -1c
.SH "Member Enumeration Documentation"
.PP 
.SS "template<typename T > anonymous enum"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIvalue \fP\fP


.SH "Author"
.PP 
Generated automatically by Doxygen for Context-Free Grammars from the source code\&.
