.TH "testing::internal::ThreadLocal< T >" 3 "Tue Jun 4 2019" "Context-Free Grammars" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::ThreadLocal< T >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gtest\-port\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBThreadLocal\fP ()"
.br
.ti -1c
.RI "\fBThreadLocal\fP (const T &value)"
.br
.ti -1c
.RI "T * \fBpointer\fP ()"
.br
.ti -1c
.RI "const T * \fBpointer\fP () const"
.br
.ti -1c
.RI "const T & \fBget\fP () const"
.br
.ti -1c
.RI "void \fBset\fP (const T &value)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename T > \fBtesting::internal::ThreadLocal\fP< T >::\fBThreadLocal\fP ()\fC [inline]\fP"

.SS "template<typename T > \fBtesting::internal::ThreadLocal\fP< T >::\fBThreadLocal\fP (const T & value)\fC [inline]\fP, \fC [explicit]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<typename T > const T& \fBtesting::internal::ThreadLocal\fP< T >::get () const\fC [inline]\fP"

.SS "template<typename T > T* \fBtesting::internal::ThreadLocal\fP< T >::pointer ()\fC [inline]\fP"

.SS "template<typename T > const T* \fBtesting::internal::ThreadLocal\fP< T >::pointer () const\fC [inline]\fP"

.SS "template<typename T > void \fBtesting::internal::ThreadLocal\fP< T >::set (const T & value)\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Context-Free Grammars from the source code\&.
