.TH "testing::internal::TestFactoryBase" 3 "Tue Jun 4 2019" "Context-Free Grammars" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::TestFactoryBase
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gtest\-internal\&.h>\fP
.PP
Inherited by \fBtesting::internal::TestFactoryImpl< TestClass >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~TestFactoryBase\fP ()"
.br
.ti -1c
.RI "virtual \fBTest\fP * \fBCreateTest\fP ()=0"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBTestFactoryBase\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "virtual testing::internal::TestFactoryBase::~TestFactoryBase ()\fC [inline]\fP, \fC [virtual]\fP"

.SS "testing::internal::TestFactoryBase::TestFactoryBase ()\fC [inline]\fP, \fC [protected]\fP"

.SH "Member Function Documentation"
.PP 
.SS "virtual \fBTest\fP* testing::internal::TestFactoryBase::CreateTest ()\fC [pure virtual]\fP"

.PP
Implemented in \fBtesting::internal::TestFactoryImpl< TestClass >\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Context-Free Grammars from the source code\&.
