.TH "testing::internal::HasNewFatalFailureHelper" 3 "Tue Jun 4 2019" "Context-Free Grammars" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::HasNewFatalFailureHelper
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gtest\-test\-part\&.h>\fP
.PP
Inherits \fBtesting::TestPartResultReporterInterface\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHasNewFatalFailureHelper\fP ()"
.br
.ti -1c
.RI "virtual \fB~HasNewFatalFailureHelper\fP ()"
.br
.ti -1c
.RI "virtual void \fBReportTestPartResult\fP (const \fBTestPartResult\fP &result)"
.br
.ti -1c
.RI "bool \fBhas_new_fatal_failure\fP () const"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "testing::internal::HasNewFatalFailureHelper::HasNewFatalFailureHelper ()"

.SS "virtual testing::internal::HasNewFatalFailureHelper::~HasNewFatalFailureHelper ()\fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "bool testing::internal::HasNewFatalFailureHelper::has_new_fatal_failure () const\fC [inline]\fP"

.SS "virtual void testing::internal::HasNewFatalFailureHelper::ReportTestPartResult (const \fBTestPartResult\fP & result)\fC [virtual]\fP"

.PP
Implements \fBtesting::TestPartResultReporterInterface\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Context-Free Grammars from the source code\&.
