.TH "testing::internal::Mutex" 3 "Tue Jun 4 2019" "Context-Free Grammars" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::Mutex
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gtest\-port\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMutex\fP ()"
.br
.ti -1c
.RI "void \fBLock\fP ()"
.br
.ti -1c
.RI "void \fBUnlock\fP ()"
.br
.ti -1c
.RI "void \fBAssertHeld\fP () const"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "testing::internal::Mutex::Mutex ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void testing::internal::Mutex::AssertHeld () const\fC [inline]\fP"

.SS "void testing::internal::Mutex::Lock ()\fC [inline]\fP"

.SS "void testing::internal::Mutex::Unlock ()\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Context-Free Grammars from the source code\&.
