.TH "testing::TestPartResultReporterInterface" 3 "Tue Jun 4 2019" "Context-Free Grammars" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::TestPartResultReporterInterface
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gtest\-test\-part\&.h>\fP
.PP
Inherited by \fBtesting::internal::HasNewFatalFailureHelper\fP, and \fBtesting::ScopedFakeTestPartResultReporter\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~TestPartResultReporterInterface\fP ()"
.br
.ti -1c
.RI "virtual void \fBReportTestPartResult\fP (const \fBTestPartResult\fP &result)=0"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "virtual testing::TestPartResultReporterInterface::~TestPartResultReporterInterface ()\fC [inline]\fP, \fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "virtual void testing::TestPartResultReporterInterface::ReportTestPartResult (const \fBTestPartResult\fP & result)\fC [pure virtual]\fP"

.PP
Implemented in \fBtesting::internal::HasNewFatalFailureHelper\fP, and \fBtesting::ScopedFakeTestPartResultReporter\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Context-Free Grammars from the source code\&.
