.TH "testing::TestProperty" 3 "Tue Jun 4 2019" "Context-Free Grammars" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::TestProperty
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gtest\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTestProperty\fP (const std::string &a_key, const std::string &a_value)"
.br
.ti -1c
.RI "const char * \fBkey\fP () const"
.br
.ti -1c
.RI "const char * \fBvalue\fP () const"
.br
.ti -1c
.RI "void \fBSetValue\fP (const std::string &new_value)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "testing::TestProperty::TestProperty (const std::string & a_key, const std::string & a_value)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "const char* testing::TestProperty::key () const\fC [inline]\fP"

.SS "void testing::TestProperty::SetValue (const std::string & new_value)\fC [inline]\fP"

.SS "const char* testing::TestProperty::value () const\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Context-Free Grammars from the source code\&.
