.TH "testing::internal::IteratorTraits< Iterator >" 3 "Tue Jun 4 2019" "Context-Free Grammars" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::IteratorTraits< Iterator >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gtest\-port\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef Iterator::value_type \fBvalue_type\fP"
.br
.in -1c
.SH "Member Typedef Documentation"
.PP 
.SS "template<typename Iterator > typedef Iterator::value_type \fBtesting::internal::IteratorTraits\fP< Iterator >::\fBvalue_type\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Context-Free Grammars from the source code\&.
