.TH "testing::internal::UniversalPrinter< T & >" 3 "Tue Jun 4 2019" "Context-Free Grammars" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::UniversalPrinter< T & >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gtest\-printers\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBPrint\fP (const T &value, ::std::ostream *os)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "template<typename T > static void \fBtesting::internal::UniversalPrinter\fP< T & >::Print (const T & value, ::std::ostream * os)\fC [inline]\fP, \fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Context-Free Grammars from the source code\&.
