.TH "testing::internal::TypeWithSize< size >" 3 "Tue Jun 4 2019" "Context-Free Grammars" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::TypeWithSize< size >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gtest\-port\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef void \fBUInt\fP"
.br
.in -1c
.SH "Member Typedef Documentation"
.PP 
.SS "template<size_t size> typedef void \fBtesting::internal::TypeWithSize\fP< size >::\fBUInt\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Context-Free Grammars from the source code\&.
