.TH "testing::internal::EnableIf< true >" 3 "Tue Jun 4 2019" "Context-Free Grammars" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::EnableIf< true >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gtest\-internal\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef void \fBtype\fP"
.br
.in -1c
.SH "Member Typedef Documentation"
.PP 
.SS "typedef void \fBtesting::internal::EnableIf\fP< true >::\fBtype\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Context-Free Grammars from the source code\&.
