.TH "testing::internal::CompileAssert< bool >" 3 "Tue Jun 4 2019" "Context-Free Grammars" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::CompileAssert< bool >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gtest\-port\&.h>\fP

.SH "Author"
.PP 
Generated automatically by Doxygen for Context-Free Grammars from the source code\&.
