.TH "testing::internal::AssertHelper" 3 "Tue Jun 4 2019" "Context-Free Grammars" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::AssertHelper
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gtest\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAssertHelper\fP (\fBTestPartResult::Type\fP type, const char *file, int line, const char *message)"
.br
.ti -1c
.RI "\fB~AssertHelper\fP ()"
.br
.ti -1c
.RI "void \fBoperator=\fP (const \fBMessage\fP &message) const"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "testing::internal::AssertHelper::AssertHelper (\fBTestPartResult::Type\fP type, const char * file, int line, const char * message)"

.SS "testing::internal::AssertHelper::~AssertHelper ()"

.SH "Member Function Documentation"
.PP 
.SS "void testing::internal::AssertHelper::operator= (const \fBMessage\fP & message) const"


.SH "Author"
.PP 
Generated automatically by Doxygen for Context-Free Grammars from the source code\&.
