.TH "testing::internal::GTestLog" 3 "Tue Jun 4 2019" "Context-Free Grammars" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::GTestLog
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gtest\-port\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGTestLog\fP (\fBGTestLogSeverity\fP severity, const char *file, int line)"
.br
.ti -1c
.RI "\fB~GTestLog\fP ()"
.br
.ti -1c
.RI "::std::ostream & \fBGetStream\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "testing::internal::GTestLog::GTestLog (\fBGTestLogSeverity\fP severity, const char * file, int line)"

.SS "testing::internal::GTestLog::~GTestLog ()"

.SH "Member Function Documentation"
.PP 
.SS "::std::ostream& testing::internal::GTestLog::GetStream ()\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Context-Free Grammars from the source code\&.
