.TH "testing::internal::ConstCharPtr" 3 "Tue Jun 4 2019" "Context-Free Grammars" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::ConstCharPtr
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gtest\-internal\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBConstCharPtr\fP (const char *str)"
.br
.ti -1c
.RI "\fBoperator bool\fP () const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const char * \fBvalue\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "testing::internal::ConstCharPtr::ConstCharPtr (const char * str)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "testing::internal::ConstCharPtr::operator bool () const\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "const char* testing::internal::ConstCharPtr::value"


.SH "Author"
.PP 
Generated automatically by Doxygen for Context-Free Grammars from the source code\&.
