.TH "testing::internal::TestFactoryImpl< TestClass >" 3 "Tue Jun 4 2019" "Context-Free Grammars" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::TestFactoryImpl< TestClass >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gtest\-internal\&.h>\fP
.PP
Inherits \fBtesting::internal::TestFactoryBase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fBTest\fP * \fBCreateTest\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Member Function Documentation"
.PP 
.SS "template<class TestClass > virtual \fBTest\fP* \fBtesting::internal::TestFactoryImpl\fP< TestClass >::CreateTest ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBtesting::internal::TestFactoryBase\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Context-Free Grammars from the source code\&.
