.TH "testing::internal::TypeIdHelper< T >" 3 "Tue Jun 4 2019" "Context-Free Grammars" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::TypeIdHelper< T >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gtest\-internal\&.h>\fP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static bool \fBdummy_\fP = false"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "template<typename T > bool \fBtesting::internal::TypeIdHelper\fP< T >::dummy_ = false\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Context-Free Grammars from the source code\&.
