.TH "testing::TestPartResultArray" 3 "Tue Jun 4 2019" "Context-Free Grammars" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::TestPartResultArray
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gtest\-test\-part\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTestPartResultArray\fP ()"
.br
.ti -1c
.RI "void \fBAppend\fP (const \fBTestPartResult\fP &result)"
.br
.ti -1c
.RI "const \fBTestPartResult\fP & \fBGetTestPartResult\fP (int index) const"
.br
.ti -1c
.RI "int \fBsize\fP () const"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "testing::TestPartResultArray::TestPartResultArray ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void testing::TestPartResultArray::Append (const \fBTestPartResult\fP & result)"

.SS "const \fBTestPartResult\fP& testing::TestPartResultArray::GetTestPartResult (int index) const"

.SS "int testing::TestPartResultArray::size () const"


.SH "Author"
.PP 
Generated automatically by Doxygen for Context-Free Grammars from the source code\&.
