.TH "ContextFreeGrammars.Deserialization/token.h" 3 "Tue Jun 4 2019" "Context-Free Grammars" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ContextFreeGrammars.Deserialization/token.h
.SH SYNOPSIS
.br
.PP
\fC#include 'stdafx\&.h'\fP
.br
\fC#include 'document_position\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBtoken\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBtoken_type\fP { \fBtoken_type::non_terminal\fP, \fBtoken_type::terminal\fP, \fBtoken_type::concatenation\fP, \fBtoken_type::choice\fP, \fBtoken_type::arrow\fP, \fBtoken_type::whitespace\fP, \fBtoken_type::semicolon\fP, \fBtoken_type::invalid_sequence\fP }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBtoken_type\fP\fC [strong]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fInon_terminal \fP\fP
.TP
\fB\fIterminal \fP\fP
.TP
\fB\fIconcatenation \fP\fP
.TP
\fB\fIchoice \fP\fP
.TP
\fB\fIarrow \fP\fP
.TP
\fB\fIwhitespace \fP\fP
.TP
\fB\fIsemicolon \fP\fP
.TP
\fB\fIinvalid_sequence \fP\fP
.SH "Author"
.PP 
Generated automatically by Doxygen for Context-Free Grammars from the source code\&.
