.TH "ContextFreeGrammars.Deserialization/tokenizer.h" 3 "Tue Jun 4 2019" "Context-Free Grammars" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ContextFreeGrammars.Deserialization/tokenizer.h
.SH SYNOPSIS
.br
.PP
\fC#include <istream>\fP
.br
\fC#include <deque>\fP
.br
\fC#include 'token\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBtokenizer\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Context-Free Grammars from the source code\&.
