.TH "tokenizer" 3 "Tue Jun 4 2019" "Context-Free Grammars" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tokenizer
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <tokenizer\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtokenizer\fP (std::istream *stream)"
.br
.ti -1c
.RI "bool \fBtry_get_next_named\fP (\fBtoken\fP *outToken=nullptr)"
.br
.ti -1c
.RI "void \fBrefeed\fP (std::istream *stream)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "tokenizer::tokenizer (std::istream * stream)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void tokenizer::refeed (std::istream * stream)"

.SS "bool tokenizer::try_get_next_named (\fBtoken\fP * outToken = \fCnullptr\fP)"


.SH "Author"
.PP 
Generated automatically by Doxygen for Context-Free Grammars from the source code\&.
