.TH "ContextFreeGrammars.Grammars/variable_arity_operator.h" 3 "Tue Jun 4 2019" "Context-Free Grammars" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ContextFreeGrammars.Grammars/variable_arity_operator.h
.SH SYNOPSIS
.br
.PP
\fC#include 'stdafx\&.h'\fP
.br
\fC#include <set>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBvariable_arity_operator< T >\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Context-Free Grammars from the source code\&.
